-- 05_011b_imposter_words_teil3von3.sql
-- Aus 011b_imposter_words.sql. Nacheinander einfuegen, Reihenfolge der Dateinamen.
-- Gefahrlos mehrfach ausfuehrbar. Erzeugt mit scripts/build-teile.mjs --
-- die Begruendungen stehen in der Ursprungsdatei.

insert into public.fdi_words (category_id, word) values
  ('koerper', 'Augenbraue'),
  ('koerper', 'Wimper'),
  ('koerper', 'Nase'),
  ('koerper', 'Mund'),
  ('koerper', 'Lippe'),
  ('koerper', 'Zahn'),
  ('koerper', 'Zunge'),
  ('koerper', 'Kinn'),
  ('koerper', 'Ohr'),
  ('koerper', 'Hals'),
  ('koerper', 'Nacken'),
  ('koerper', 'Schulter'),
  ('koerper', 'Arm'),
  ('koerper', 'Ellenbogen'),
  ('koerper', 'Handgelenk'),
  ('koerper', 'Hand'),
  ('koerper', 'Finger'),
  ('koerper', 'Daumen'),
  ('koerper', 'Fingernagel'),
  ('koerper', 'Brustkorb'),
  ('koerper', 'Bauch'),
  ('koerper', 'Rücken'),
  ('koerper', 'Hüfte'),
  ('koerper', 'Bein'),
  ('koerper', 'Knie'),
  ('koerper', 'Wade'),
  ('koerper', 'Knöchel'),
  ('koerper', 'Fuß'),
  ('koerper', 'Zeh'),
  ('koerper', 'Ferse'),
  ('koerper', 'Haut'),
  ('koerper', 'Muskel'),
  ('koerper', 'Knochen'),
  ('koerper', 'Herz'),
  ('koerper', 'Lunge'),
  ('koerper', 'Magen'),
  ('koerper', 'Leber'),
  ('koerper', 'Niere'),
  ('koerper', 'Gehirn'),
  ('koerper', 'Blut'),
  ('koerper', 'Puls'),
  ('koerper', 'Fieber'),
  ('koerper', 'Husten'),
  ('koerper', 'Schnupfen'),
  ('koerper', 'Kopfschmerzen'),
  ('koerper', 'Pflaster'),
  ('kleidung', 'Hemd'),
  ('kleidung', 'Bluse'),
  ('kleidung', 'T-Shirt'),
  ('kleidung', 'Pullover'),
  ('kleidung', 'Strickjacke'),
  ('kleidung', 'Weste'),
  ('kleidung', 'Jacke'),
  ('kleidung', 'Mantel'),
  ('kleidung', 'Anorak'),
  ('kleidung', 'Regenjacke'),
  ('kleidung', 'Hose'),
  ('kleidung', 'Jeans'),
  ('kleidung', 'Shorts'),
  ('kleidung', 'Rock'),
  ('kleidung', 'Kleid'),
  ('kleidung', 'Anzug'),
  ('kleidung', 'Krawatte'),
  ('kleidung', 'Fliege'),
  ('kleidung', 'Gürtel'),
  ('kleidung', 'Hosenträger'),
  ('kleidung', 'Socken'),
  ('kleidung', 'Strumpfhose'),
  ('kleidung', 'Unterhemd'),
  ('kleidung', 'Schlafanzug'),
  ('kleidung', 'Bademantel'),
  ('kleidung', 'Badehose'),
  ('kleidung', 'Badeanzug'),
  ('kleidung', 'Bikini'),
  ('kleidung', 'Turnschuhe'),
  ('kleidung', 'Sandalen'),
  ('kleidung', 'Stiefel'),
  ('kleidung', 'Gummistiefel'),
  ('kleidung', 'Hausschuhe'),
  ('kleidung', 'Wanderschuhe'),
  ('kleidung', 'Mütze'),
  ('kleidung', 'Hut'),
  ('kleidung', 'Kappe'),
  ('kleidung', 'Schal'),
  ('kleidung', 'Handschuhe'),
  ('kleidung', 'Halstuch'),
  ('kleidung', 'Brille'),
  ('kleidung', 'Sonnenbrille'),
  ('kleidung', 'Armbanduhr'),
  ('kleidung', 'Ring'),
  ('kleidung', 'Halskette'),
  ('kleidung', 'Ohrring'),
  ('kleidung', 'Handtasche'),
  ('kleidung', 'Geldbeutel'),
  ('kleidung', 'Regenschirm'),
  ('kleidung', 'Lätzchen'),
  ('fahrzeuge', 'Auto'),
  ('fahrzeuge', 'Fahrrad'),
  ('fahrzeuge', 'Motorrad'),
  ('fahrzeuge', 'Roller'),
  ('fahrzeuge', 'Moped'),
  ('fahrzeuge', 'Lastwagen'),
  ('fahrzeuge', 'Lieferwagen'),
  ('fahrzeuge', 'Bus'),
  ('fahrzeuge', 'Reisebus'),
  ('fahrzeuge', 'Straßenbahn'),
  ('fahrzeuge', 'U-Bahn'),
  ('fahrzeuge', 'S-Bahn'),
  ('fahrzeuge', 'Zug'),
  ('fahrzeuge', 'Lokomotive'),
  ('fahrzeuge', 'Güterzug'),
  ('fahrzeuge', 'Taxi'),
  ('fahrzeuge', 'Krankenwagen'),
  ('fahrzeuge', 'Feuerwehrauto'),
  ('fahrzeuge', 'Polizeiauto'),
  ('fahrzeuge', 'Müllwagen'),
  ('fahrzeuge', 'Traktor'),
  ('fahrzeuge', 'Mähdrescher'),
  ('fahrzeuge', 'Bagger'),
  ('fahrzeuge', 'Kran'),
  ('fahrzeuge', 'Gabelstapler'),
  ('fahrzeuge', 'Betonmischer'),
  ('fahrzeuge', 'Schneepflug'),
  ('fahrzeuge', 'Wohnmobil'),
  ('fahrzeuge', 'Anhänger'),
  ('fahrzeuge', 'Cabrio'),
  ('fahrzeuge', 'Geländewagen'),
  ('fahrzeuge', 'Sportwagen'),
  ('fahrzeuge', 'Oldtimer'),
  ('fahrzeuge', 'Rennwagen'),
  ('fahrzeuge', 'Flugzeug'),
  ('fahrzeuge', 'Hubschrauber'),
  ('fahrzeuge', 'Segelflugzeug'),
  ('fahrzeuge', 'Heißluftballon'),
  ('fahrzeuge', 'Rakete'),
  ('fahrzeuge', 'Schiff'),
  ('fahrzeuge', 'Segelboot'),
  ('fahrzeuge', 'Ruderboot'),
  ('fahrzeuge', 'Kanu'),
  ('fahrzeuge', 'Schlauchboot'),
  ('fahrzeuge', 'U-Boot'),
  ('fahrzeuge', 'Jetski'),
  ('fahrzeuge', 'Seilbahn'),
  ('fahrzeuge', 'Skilift'),
  ('fahrzeuge', 'Rollstuhl'),
  ('fahrzeuge', 'Tretroller'),
  ('spiele', 'Schach'),
  ('spiele', 'Dame'),
  ('spiele', 'Mühle'),
  ('spiele', 'Halma'),
  ('spiele', 'Backgammon'),
  ('spiele', 'Mensch ärgere dich nicht'),
  ('spiele', 'Monopoly'),
  ('spiele', 'Scrabble'),
  ('spiele', 'Risiko'),
  ('spiele', 'Die Siedler von Catan'),
  ('spiele', 'Uno'),
  ('spiele', 'Skat'),
  ('spiele', 'Doppelkopf'),
  ('spiele', 'Rommé'),
  ('spiele', 'Mau-Mau'),
  ('spiele', 'Poker'),
  ('spiele', 'Memory'),
  ('spiele', 'Puzzle'),
  ('spiele', 'Domino'),
  ('spiele', 'Kniffel'),
  ('spiele', 'Bingo'),
  ('spiele', 'Sudoku'),
  ('spiele', 'Kreuzworträtsel'),
  ('spiele', 'Verstecken'),
  ('spiele', 'Fangen'),
  ('spiele', 'Blinde Kuh'),
  ('spiele', 'Topfschlagen'),
  ('spiele', 'Reise nach Jerusalem'),
  ('spiele', 'Stille Post'),
  ('spiele', 'Sackhüpfen'),
  ('spiele', 'Gummitwist'),
  ('spiele', 'Seilspringen'),
  ('spiele', 'Hüpfkästchen'),
  ('spiele', 'Murmeln'),
  ('spiele', 'Drachensteigen'),
  ('spiele', 'Sandburg'),
  ('spiele', 'Schaukel'),
  ('spiele', 'Rutsche'),
  ('spiele', 'Wippe'),
  ('spiele', 'Klettergerüst'),
  ('spiele', 'Lego'),
  ('spiele', 'Playmobil'),
  ('spiele', 'Modelleisenbahn'),
  ('spiele', 'Sammelalbum'),
  ('spiele', 'Briefmarken'),
  ('spiele', 'Stricken'),
  ('spiele', 'Häkeln'),
  ('spiele', 'Basteln'),
  ('spiele', 'Gartenarbeit'),
  ('spiele', 'Angeln'),
  ('feiertage', 'Weihnachten'),
  ('feiertage', 'Heiligabend'),
  ('feiertage', 'Silvester'),
  ('feiertage', 'Neujahr'),
  ('feiertage', 'Ostern'),
  ('feiertage', 'Karfreitag'),
  ('feiertage', 'Pfingsten'),
  ('feiertage', 'Fronleichnam'),
  ('feiertage', 'Christi Himmelfahrt'),
  ('feiertage', 'Nikolaus'),
  ('feiertage', 'Advent'),
  ('feiertage', 'Adventskranz'),
  ('feiertage', 'Weihnachtsbaum'),
  ('feiertage', 'Krippe'),
  ('feiertage', 'Weihnachtsmarkt'),
  ('feiertage', 'Plätzchen'),
  ('feiertage', 'Osterhase'),
  ('feiertage', 'Ostereier'),
  ('feiertage', 'Eiersuche'),
  ('feiertage', 'Karneval'),
  ('feiertage', 'Fasching'),
  ('feiertage', 'Rosenmontag'),
  ('feiertage', 'Aschermittwoch'),
  ('feiertage', 'Muttertag'),
  ('feiertage', 'Vatertag'),
  ('feiertage', 'Valentinstag'),
  ('feiertage', 'Halloween'),
  ('feiertage', 'Erntedankfest'),
  ('feiertage', 'Martinstag'),
  ('feiertage', 'Laternenumzug'),
  ('feiertage', 'Schützenfest'),
  ('feiertage', 'Oktoberfest'),
  ('feiertage', 'Kirmes'),
  ('feiertage', 'Jahrmarkt'),
  ('feiertage', 'Geburtstag'),
  ('feiertage', 'Geburtstagstorte'),
  ('feiertage', 'Hochzeit'),
  ('feiertage', 'Polterabend'),
  ('feiertage', 'Taufe'),
  ('feiertage', 'Kommunion'),
  ('feiertage', 'Konfirmation'),
  ('feiertage', 'Jubiläum'),
  ('feiertage', 'Richtfest'),
  ('feiertage', 'Einschulung'),
  ('feiertage', 'Abschlussfeier'),
  ('feiertage', 'Feuerwerk'),
  ('feiertage', 'Girlande'),
  ('feiertage', 'Luftballon'),
  ('feiertage', 'Geschenk'),
  ('feiertage', 'Festessen'),
  ('gefuehle', 'Freude'),
  ('gefuehle', 'Glück'),
  ('gefuehle', 'Liebe'),
  ('gefuehle', 'Zuneigung'),
  ('gefuehle', 'Stolz'),
  ('gefuehle', 'Dankbarkeit'),
  ('gefuehle', 'Erleichterung'),
  ('gefuehle', 'Hoffnung'),
  ('gefuehle', 'Vorfreude'),
  ('gefuehle', 'Neugier'),
  ('gefuehle', 'Begeisterung'),
  ('gefuehle', 'Zufriedenheit'),
  ('gefuehle', 'Geborgenheit'),
  ('gefuehle', 'Mitgefühl'),
  ('gefuehle', 'Sehnsucht'),
  ('gefuehle', 'Heimweh'),
  ('gefuehle', 'Fernweh'),
  ('gefuehle', 'Traurigkeit'),
  ('gefuehle', 'Kummer'),
  ('gefuehle', 'Enttäuschung'),
  ('gefuehle', 'Wut'),
  ('gefuehle', 'Ärger'),
  ('gefuehle', 'Zorn'),
  ('gefuehle', 'Frust'),
  ('gefuehle', 'Neid'),
  ('gefuehle', 'Eifersucht'),
  ('gefuehle', 'Angst'),
  ('gefuehle', 'Panik'),
  ('gefuehle', 'Sorge'),
  ('gefuehle', 'Nervosität'),
  ('gefuehle', 'Aufregung'),
  ('gefuehle', 'Scham'),
  ('gefuehle', 'Schuldgefühl'),
  ('gefuehle', 'Verlegenheit'),
  ('gefuehle', 'Peinlichkeit'),
  ('gefuehle', 'Langeweile'),
  ('gefuehle', 'Müdigkeit'),
  ('gefuehle', 'Erschöpfung'),
  ('gefuehle', 'Überraschung'),
  ('gefuehle', 'Verwirrung'),
  ('gefuehle', 'Zweifel'),
  ('gefuehle', 'Misstrauen'),
  ('gefuehle', 'Einsamkeit'),
  ('gefuehle', 'Heiterkeit'),
  ('gefuehle', 'Schadenfreude'),
  ('gefuehle', 'Gelassenheit'),
  ('gefuehle', 'Ungeduld'),
  ('gefuehle', 'Respekt'),
  ('gefuehle', 'Bewunderung'),
  ('gefuehle', 'Zuversicht'),
  ('stadt', 'Rathaus'),
  ('stadt', 'Marktplatz'),
  ('stadt', 'Kirche'),
  ('stadt', 'Dom'),
  ('stadt', 'Bushaltestelle'),
  ('stadt', 'Fußgängerzone'),
  ('stadt', 'Einkaufszentrum'),
  ('stadt', 'Supermarkt'),
  ('stadt', 'Bäckerei'),
  ('stadt', 'Metzgerei'),
  ('stadt', 'Apotheke'),
  ('stadt', 'Drogerie'),
  ('stadt', 'Buchhandlung'),
  ('stadt', 'Blumenladen'),
  ('stadt', 'Kiosk'),
  ('stadt', 'Postfiliale'),
  ('stadt', 'Bank'),
  ('stadt', 'Geldautomat'),
  ('stadt', 'Bibliothek'),
  ('stadt', 'Schwimmbad'),
  ('stadt', 'Sporthalle'),
  ('stadt', 'Stadion'),
  ('stadt', 'Kino'),
  ('stadt', 'Theater'),
  ('stadt', 'Stadtmuseum'),
  ('stadt', 'Zoo'),
  ('stadt', 'Stadtpark'),
  ('stadt', 'Spielplatz'),
  ('stadt', 'Friedhof'),
  ('stadt', 'Krankenhaus'),
  ('stadt', 'Feuerwache'),
  ('stadt', 'Polizeirevier'),
  ('stadt', 'Ampel'),
  ('stadt', 'Zebrastreifen'),
  ('stadt', 'Kreisverkehr'),
  ('stadt', 'Parkhaus'),
  ('stadt', 'Baustelle'),
  ('stadt', 'Straßenlaterne'),
  ('stadt', 'Mülleimer'),
  ('stadt', 'Parkbank'),
  ('stadt', 'Brunnen'),
  ('stadt', 'Denkmal'),
  ('stadt', 'Brücke'),
  ('stadt', 'Tunnel'),
  ('stadt', 'Stau'),
  ('stadt', 'Radweg'),
  ('stadt', 'Bürgersteig'),
  ('stadt', 'Hochhaus'),
  ('stadt', 'Fahrkartenautomat'),
  ('stadt', 'Wochenmarkt'),
  ('maerchen', 'Schneewittchen'),
  ('maerchen', 'Aschenputtel'),
  ('maerchen', 'Dornröschen'),
  ('maerchen', 'Rotkäppchen'),
  ('maerchen', 'Rapunzel'),
  ('maerchen', 'Hänsel und Gretel'),
  ('maerchen', 'Frau Holle'),
  ('maerchen', 'Rumpelstilzchen'),
  ('maerchen', 'Der Froschkönig'),
  ('maerchen', 'Die Bremer Stadtmusikanten'),
  ('maerchen', 'Der gestiefelte Kater'),
  ('maerchen', 'Tischlein deck dich'),
  ('maerchen', 'Das tapfere Schneiderlein'),
  ('maerchen', 'Die Sterntaler'),
  ('maerchen', 'Der Wolf und die sieben Geißlein'),
  ('maerchen', 'Peter Pan'),
  ('maerchen', 'Pinocchio'),
  ('maerchen', 'Alice im Wunderland'),
  ('maerchen', 'Der kleine Prinz'),
  ('maerchen', 'Robin Hood'),
  ('maerchen', 'König Artus'),
  ('maerchen', 'Drache'),
  ('maerchen', 'Ritter'),
  ('maerchen', 'Prinzessin'),
  ('maerchen', 'Prinz'),
  ('maerchen', 'König'),
  ('maerchen', 'Königin'),
  ('maerchen', 'Hexe'),
  ('maerchen', 'Zauberer'),
  ('maerchen', 'Fee'),
  ('maerchen', 'Elfe'),
  ('maerchen', 'Zwerg'),
  ('maerchen', 'Riese'),
  ('maerchen', 'Troll'),
  ('maerchen', 'Kobold'),
  ('maerchen', 'Einhorn'),
  ('maerchen', 'Meerjungfrau'),
  ('maerchen', 'Vampir'),
  ('maerchen', 'Werwolf'),
  ('maerchen', 'Gespenst'),
  ('maerchen', 'Zauberstab'),
  ('maerchen', 'Zaubertrank'),
  ('maerchen', 'Zauberspiegel'),
  ('maerchen', 'Märchenschloss'),
  ('maerchen', 'Verwunschener Wald'),
  ('maerchen', 'Goldene Kugel'),
  ('maerchen', 'Glasschuh'),
  ('maerchen', 'Spinnrad'),
  ('maerchen', 'Siebenmeilenstiefel'),
  ('maerchen', 'Wunschbrunnen'),
  ('beruehmt', 'Albert Einstein'),
  ('beruehmt', 'Isaac Newton'),
  ('beruehmt', 'Marie Curie'),
  ('beruehmt', 'Charles Darwin'),
  ('beruehmt', 'Leonardo da Vinci'),
  ('beruehmt', 'Michelangelo'),
  ('beruehmt', 'Vincent van Gogh'),
  ('beruehmt', 'Pablo Picasso'),
  ('beruehmt', 'Ludwig van Beethoven'),
  ('beruehmt', 'Wolfgang Amadeus Mozart'),
  ('beruehmt', 'Johann Sebastian Bach'),
  ('beruehmt', 'Johann Wolfgang von Goethe'),
  ('beruehmt', 'Friedrich Schiller'),
  ('beruehmt', 'Die Gebrüder Grimm'),
  ('beruehmt', 'William Shakespeare'),
  ('beruehmt', 'Astrid Lindgren'),
  ('beruehmt', 'Anne Frank'),
  ('beruehmt', 'Martin Luther'),
  ('beruehmt', 'Martin Luther King'),
  ('beruehmt', 'Mahatma Gandhi'),
  ('beruehmt', 'Nelson Mandela'),
  ('beruehmt', 'Mutter Teresa'),
  ('beruehmt', 'Winston Churchill'),
  ('beruehmt', 'Konrad Adenauer'),
  ('beruehmt', 'Angela Merkel'),
  ('beruehmt', 'Helmut Kohl'),
  ('beruehmt', 'Christoph Kolumbus'),
  ('beruehmt', 'Neil Armstrong'),
  ('beruehmt', 'Alexander von Humboldt'),
  ('beruehmt', 'Karl der Große'),
  ('beruehmt', 'Napoleon'),
  ('beruehmt', 'Kleopatra'),
  ('beruehmt', 'Julius Cäsar'),
  ('beruehmt', 'Elvis Presley'),
  ('beruehmt', 'Michael Jackson'),
  ('beruehmt', 'Die Beatles'),
  ('beruehmt', 'Freddie Mercury'),
  ('beruehmt', 'Marilyn Monroe'),
  ('beruehmt', 'Charlie Chaplin'),
  ('beruehmt', 'Walt Disney'),
  ('beruehmt', 'Steve Jobs'),
  ('beruehmt', 'Bill Gates'),
  ('beruehmt', 'Muhammad Ali'),
  ('beruehmt', 'Pelé'),
  ('beruehmt', 'Franz Beckenbauer'),
  ('beruehmt', 'Michael Schumacher'),
  ('beruehmt', 'Steffi Graf'),
  ('beruehmt', 'Boris Becker'),
  ('beruehmt', 'Dirk Nowitzki'),
  ('beruehmt', 'Usain Bolt')
on conflict (category_id, word) do nothing;
