/**
 * Die Fragen für „Wer würde eher?".
 *
 * Zwei Sorten:
 *   personen  – „Wer würde am ehesten …?" Alle tippen auf einen Namen.
 *   entweder  – „Was wäre dir lieber?" Alle entscheiden sich für A oder B.
 *
 * Alles familientauglich gehalten: Das Spiel soll auch funktionieren, wenn
 * Oma mitspielt. Nichts über Aussehen, Geld oder Beziehungen -- daran gehen
 * Partyspiele kaputt, nicht am fehlenden Witz.
 */

export type FrageModus = 'personen' | 'entweder'

export interface Frage {
  id: string
  modus: FrageModus
  text: string
  /** Nur bei „entweder": die beiden Möglichkeiten. */
  a?: string
  b?: string
}

const PERSONEN: string[] = [
  'verschläft und zu spät zum Flughafen kommt',
  'einen ganzen Kuchen alleine isst',
  'sich im eigenen Wohnort verläuft',
  'bei einem Horrorfilm zuerst schreit',
  'als Erster auf der Tanzfläche steht',
  'sein Handy in die Toilette fallen lässt',
  'einen Tag ohne Kaffee nicht übersteht',
  'beim Wandern die Karte falsch herum hält',
  'einen Streit über die richtige Nudelsorte anfängt',
  'im Supermarkt vergisst, was er kaufen wollte',
  'freiwillig auf einer Bühne singt',
  'eine Woche ohne Fernsehen aushält',
  'sich beim Grillen die Wurst verbrennen lässt',
  'auf dem Weihnachtsmarkt als Letzter nach Hause geht',
  'aus Versehen im falschen Zug sitzt',
  'jeden Geburtstag im Kalender kennt',
  'einen Regenschirm dabeihat, wenn es regnet',
  'ein Möbelstück ohne Anleitung zusammenbaut',
  'nach zwei Minuten aufgibt und die Anleitung holt',
  'zu Silvester als Erster einschläft',
  'seine Schlüssel im Kühlschrank wiederfindet',
  'sich mit dem Nachbarn über die Hecke streitet',
  'freiwillig den Abwasch macht',
  'beim Kartenspiel schummelt',
  'beim Kartenspiel erwischt wird',
  'eine Reise bis auf die Minute durchplant',
  'ohne Plan ins Auto steigt und losfährt',
  'jedem Hund auf der Straße Hallo sagt',
  'sich beim Zelten über die Ameisen beschwert',
  'im Restaurant immer dasselbe bestellt',
  'die schärfste Sauce probiert',
  'beim Fußball am lautesten schreit',
  'behauptet, den Weg zu kennen, und ihn nicht kennt',
  'im Urlaub zuerst ins kalte Wasser springt',
  'am längsten braucht, um sich fertig zu machen',
  'als Erster von einem neuen Handy erzählt',
  'noch ein altes Nokia in der Schublade hat',
  'am Wochenende bis mittags schläft',
  'schon um sechs Uhr wach ist und Frühstück macht',
  'einen Berg hochläuft, statt die Bahn zu nehmen',
  'einen Marathon anmeldet und wirklich hinläuft',
  'sich freiwillig für die Vereinsarbeit meldet',
  'einen Tag Bürgermeister sein möchte',
  'nie ein Foto von sich mag',
  'von jedem Essen ein Foto macht',
  'die Blumen im Urlaub vergisst zu gießen',
  'auf jedem Fest den Grill übernimmt',
  'am längsten braucht, um einen Text zu tippen',
  'aus Versehen alle in einer Gruppe anschreibt',
  'sich beim Wandern über Blasen beschwert',
  'die ganze Serie an einem Wochenende schaut',
  'die Serie nach drei Folgen aufgibt',
  'ein Instrument lernt, nur um es einmal zu spielen',
  'einen Kuchen backt, der nach Rezept aussieht',
  'die Küche danach so hinterlässt, wie sie war',
  'am ehesten eine Spinne rausträgt statt sie zu töten',
  'am ehesten auf einen Stuhl steigt, wenn eine Maus kommt',
  'im Sommer die Heizung anmacht',
  'im Winter das Fenster aufreißt',
  'nach dem Essen noch einen Nachtisch schafft',
  'die letzte Praline nimmt',
  'die letzte Praline liegen lässt, damit keiner streitet',
  'einen alten Freund nach zehn Jahren einfach anruft',
  'im Wartezimmer mit Fremden ins Gespräch kommt',
  'im Aufzug schweigt und an die Decke schaut',
  'sich über den Kassenbon beschwert',
  'im Baumarkt eine Stunde vor den Schrauben steht',
  'zum Sperrmüll fährt, nur um zu schauen',
  'aus einer Palette einen Tisch baut',
  'jeden Werkzeugkasten sortiert hat',
  'das Werkzeug nie zurückbringt',
  'ein Rezept nach Gefühl abwandelt',
  'sich exakt an das Rezept hält',
  'die längste Sprachnachricht schickt',
  'nie ans Telefon geht',
  'auf jede Frage eine Geschichte erzählt',
  'am wenigsten sagt und am meisten mitbekommt',
  'bei einem Quiz alle Antworten kennt',
  'bei einem Quiz mit voller Überzeugung falsch liegt',
  'die Kaffeemaschine als Erster morgens anwirft',
  'sich beim Einparken zehnmal neu ansetzt',
  'rückwärts in eine Lücke fährt, in die keiner passt',
  'einen Zug verpasst, obwohl er zwanzig Minuten früher da war',
  'in der Schlange am längsten wartet, ohne zu murren',
  'am Buffet als Erster ansteht',
  'im Kino den ganzen Popcornbecher leert, bevor der Film anfängt',
  'im Kino einschläft',
  'jedes Detail aus dem Film noch Jahre später weiß',
  'sich einen Fernseher kauft, der zu groß fürs Zimmer ist',
  'die Bedienungsanleitung wirklich liest',
  'jede Steckdose im Haus kennt',
  'die Uhr am Herd nie umgestellt hat',
  'nach der Zeitumstellung zwei Wochen zu früh kommt',
  'seine Bahncard immer dabeihat',
  'immer genau abgezählt bezahlt',
  'nie Bargeld dabeihat',
  'als Erster ein neues Gerät ausprobiert',
  'ein Gerät kauft und die Kiste nie aufmacht',
  'jedes Kabel aufhebt, weil man es noch brauchen könnte',
  'am Ende alles wegwirft und neu kauft',
  'ein Zimmer streicht, ohne abzukleben',
  'drei Stunden abklebt und dann nicht mehr streicht',
  'sich freiwillig um den Papierkram kümmert',
  'die Steuererklärung am letzten Tag macht',
  'die Wanderschuhe schon im Februar putzt',
  'einen Ausflug bei Regen trotzdem durchzieht',
  'sofort umdreht, wenn es tröpfelt',
  'im Zelt am besten schläft',
  'nach einer Nacht im Zelt ein Hotel bucht',
  'einen Sonnenbrand mit nach Hause bringt',
  'im Urlaub die meisten Postkarten schreibt',
  'behauptet, sich alles zu merken, und nichts aufschreibt',
]

const ENTWEDER: [string, string][] = [
  ['Nie wieder Kaffee', 'Nie wieder Schokolade'],
  ['Immer zu früh sein', 'Immer fünf Minuten zu spät'],
  ['Eine Woche ohne Handy', 'Eine Woche ohne Musik'],
  ['Im Wald übernachten', 'Am Bahnhof übernachten'],
  ['Nur noch Sommer', 'Nur noch Winter'],
  ['Fliegen können', 'Unsichtbar sein'],
  ['Jede Sprache verstehen', 'Mit Tieren reden können'],
  ['Immer die Wahrheit sagen müssen', 'Nie mehr etwas erklären dürfen'],
  ['Berge', 'Meer'],
  ['Selber kochen', 'Immer abwaschen'],
  ['Nie wieder Fernsehen', 'Nie wieder Radio'],
  ['Zu Fuß zur Arbeit', 'Eine Stunde im Stau'],
  ['Einen Tag König sein', 'Ein Jahr keine Rechnungen zahlen'],
  ['Nur Süßes essen dürfen', 'Nur Salziges essen dürfen'],
  ['Immer frieren', 'Immer schwitzen'],
  ['Eine Stunde früher aufstehen', 'Eine Stunde später ins Bett'],
  ['Ohne Internet leben', 'Ohne Auto leben'],
  ['Immer barfuß', 'Immer mit Mütze'],
  ['Nie wieder Pizza', 'Nie wieder Pommes'],
  ['Alles über die Zukunft wissen', 'Alles über die Vergangenheit wissen'],
  ['Ein großes Fest', 'Ein ruhiger Abend zu zweit'],
  ['Ein Haus im Dorf', 'Eine Wohnung in der Stadt'],
  ['Immer laute Musik nebenan', 'Immer eine tropfende Leitung'],
  ['Jeden Tag dasselbe essen', 'Jeden Tag etwas, das du nicht kennst'],
  ['Nie mehr schwimmen', 'Nie mehr wandern'],
  ['Zehn Kilometer laufen', 'Zwei Stunden Rasen mähen'],
  ['Einen Monat kein Fleisch', 'Einen Monat kein Brot'],
  ['Nie wieder ein Buch lesen', 'Nie wieder einen Film sehen'],
  ['Beim Zahnarzt sitzen', 'Beim Finanzamt anrufen'],
  ['Immer die Rechnung übernehmen', 'Nie ausgehen'],
  ['Einen Tag im Regen wandern', 'Einen Tag im Wartezimmer'],
  ['Auf einer einsamen Insel', 'In einer riesigen Stadt'],
  ['Ohne Uhr leben', 'Ohne Kalender leben'],
  ['Immer singen müssen', 'Immer flüstern müssen'],
  ['Deinen Lieblingsplatz nie wiedersehen', 'Nie wieder verreisen'],
  ['Nur noch kalt duschen', 'Nur noch im Dunkeln duschen'],
  ['Ein Instrument perfekt können', 'Fünf Sprachen sprechen'],
  ['Immer gewinnen, aber alleine spielen', 'Immer verlieren, aber in guter Runde'],
  ['Die Wohnung putzen', 'Den Keller aufräumen'],
  ['Eine Woche Camping bei Regen', 'Eine Woche Hotel ohne Fenster'],
  ['Nie wieder Kuchen', 'Nie wieder Eis'],
  ['Immer die erste Reihe', 'Immer der letzte Platz'],
  ['Zu einem Umzug helfen', 'Einen Tag Kinder hüten'],
  ['Nur Radio hören', 'Nur Zeitung lesen'],
  ['Jeden Sonntag Besuch', 'Nie Besuch'],
  ['Immer alles allein entscheiden', 'Nie etwas entscheiden müssen'],
  ['Ein Jahr ohne Süßigkeiten', 'Ein Jahr ohne Urlaub'],
  ['Der Erste sein, der etwas erfährt', 'Der Letzte, aber die ganze Geschichte hören'],
  ['Deine Lieblingsserie neu erleben dürfen', 'Ein neues Hobby geschenkt bekommen'],
  ['Nie mehr frieren', 'Nie mehr müde sein'],
  ['Alles reparieren können', 'Alles kochen können'],
  ['Ein Tag ganz ohne Termine', 'Eine Woche mit halb so vielen'],
  ['Immer laut lachen', 'Immer leise grinsen'],
  ['Immer den Fensterplatz', 'Immer den Gangplatz'],
  ['Nur Treppen steigen', 'Nur Fahrstuhl fahren'],
  ['Eine Stunde im Schnee stehen', 'Eine Stunde in der prallen Sonne'],
  ['Nie wieder Kartoffeln', 'Nie wieder Nudeln'],
  ['Alles selbst anbauen', 'Alles selbst backen'],
  ['Auf dem Boden schlafen', 'Im Sitzen schlafen'],
  ['Immer den Weg erklären müssen', 'Immer nach dem Weg fragen müssen'],
  ['Ein Zimmer voller Bücher', 'Ein Zimmer voller Werkzeug'],
  ['Nie wieder verschlafen', 'Nie wieder Kopfschmerzen'],
  ['Immer die Musik aussuchen', 'Immer fahren dürfen'],
  ['Einen Tag jemand anderes sein', 'Einen Tag alles vergessen'],
  ['Zwei Stunden anstehen', 'Zwei Stunden telefonisch in der Warteschleife'],
  ['Immer im Chor singen', 'Immer allein pfeifen'],
  ['Nie wieder Handschuhe verlieren', 'Nie wieder eine Socke verlieren'],
  ['Ein Feuerwerk allein sehen', 'Kein Feuerwerk, aber in großer Runde'],
  ['Jeden Tag ein bisschen Sport', 'Einmal die Woche richtig viel'],
  ['Alles aufschreiben müssen', 'Alles auswendig lernen müssen'],
  ['Ein Tag ohne Strom', 'Ein Tag ohne Wasser'],
  ['Immer Suppe zum Abendessen', 'Immer Brot zum Mittagessen'],
  ['Eine große Reise im Leben', 'Jedes Jahr ein kleiner Ausflug'],
  ['Immer der Erste am Buffet', 'Immer der Letzte, aber es bleibt genug'],
  ['Nie wieder Streit', 'Nie wieder Langeweile'],
  ['Ein Haustier, das redet', 'Ein Auto, das selbst fährt'],
  ['Alles doppelt so schnell tun', 'Doppelt so viel Zeit haben'],
  ['Nur noch Postkarten schreiben', 'Nur noch anrufen'],
  ['Eine Woche allein im Ferienhaus', 'Eine Woche mit zehn Leuten im Zelt'],
  ['Nie wieder einen Termin vergessen', 'Nie wieder einen Namen vergessen'],
]

export const FRAGEN: Frage[] = [
  ...PERSONEN.map((text, i) => ({
    id: `p${i}`,
    modus: 'personen' as const,
    text: `Wer würde am ehesten … ${text}?`,
  })),
  ...ENTWEDER.map(([a, b], i) => ({
    id: `e${i}`,
    modus: 'entweder' as const,
    text: 'Was wäre dir lieber?',
    a,
    b,
  })),
]

export function fragenFuer(modi: FrageModus[]): Frage[] {
  const erlaubt = modi.length > 0 ? modi : (['personen', 'entweder'] as FrageModus[])
  return FRAGEN.filter((f) => erlaubt.includes(f.modus))
}
