-- Wörter und Kategorien für das Online-Spiel "Finde den Imposter".
--
-- NICHT von Hand pflegen: erzeugt aus src/games/finde-den-imposter/data/ mit
--   node scripts/build-imposter-words-sql.mjs
-- tests/imposter-words-sql.test.ts schlägt fehl, sobald beides auseinanderläuft.
--
-- Der Server zieht das geheime Wort selbst -- würde der Gastgeber es im
-- Browser auswählen, kennte er es auch als Imposter.

insert into public.fdi_categories (id, label) values
  ('tiere', 'Tiere'),
  ('essen', 'Essen & Trinken'),
  ('berufe', 'Berufe'),
  ('sport', 'Sport'),
  ('reisen', 'Reisen & Orte'),
  ('technik', 'Technik'),
  ('filme', 'Filme & Serien'),
  ('musik', 'Musik'),
  ('schule', 'Schule & Lernen'),
  ('haus', 'Haus & Wohnen'),
  ('natur', 'Natur & Wetter'),
  ('koerper', 'Körper & Gesundheit'),
  ('kleidung', 'Kleidung'),
  ('fahrzeuge', 'Fahrzeuge'),
  ('spiele', 'Spiele & Hobbys'),
  ('feiertage', 'Feiertage & Feste'),
  ('gefuehle', 'Gefühle'),
  ('stadt', 'Stadt & Alltag'),
  ('maerchen', 'Märchen & Fantasie'),
  ('beruehmt', 'Berühmte Personen')
on conflict (id) do update set label = excluded.label;

insert into public.fdi_words (category_id, word) values
  ('tiere', 'Hund'),
  ('tiere', 'Katze'),
  ('tiere', 'Pferd'),
  ('tiere', 'Kuh'),
  ('tiere', 'Schwein'),
  ('tiere', 'Huhn'),
  ('tiere', 'Ente'),
  ('tiere', 'Gans'),
  ('tiere', 'Schaf'),
  ('tiere', 'Ziege'),
  ('tiere', 'Hase'),
  ('tiere', 'Fuchs'),
  ('tiere', 'Wolf'),
  ('tiere', 'Bär'),
  ('tiere', 'Löwe'),
  ('tiere', 'Tiger'),
  ('tiere', 'Elefant'),
  ('tiere', 'Giraffe'),
  ('tiere', 'Affe'),
  ('tiere', 'Pinguin'),
  ('tiere', 'Delfin'),
  ('tiere', 'Hai'),
  ('tiere', 'Wal'),
  ('tiere', 'Adler'),
  ('tiere', 'Eule'),
  ('tiere', 'Spatz'),
  ('tiere', 'Storch'),
  ('tiere', 'Biene'),
  ('tiere', 'Ameise'),
  ('tiere', 'Spinne'),
  ('tiere', 'Schmetterling'),
  ('tiere', 'Frosch'),
  ('tiere', 'Schildkröte'),
  ('tiere', 'Schlange'),
  ('tiere', 'Krokodil'),
  ('tiere', 'Igel'),
  ('tiere', 'Eichhörnchen'),
  ('tiere', 'Maus'),
  ('tiere', 'Ratte'),
  ('tiere', 'Fledermaus'),
  ('tiere', 'Reh'),
  ('tiere', 'Hirsch'),
  ('tiere', 'Wildschwein'),
  ('tiere', 'Kamel'),
  ('tiere', 'Zebra'),
  ('tiere', 'Nashorn'),
  ('tiere', 'Nilpferd'),
  ('tiere', 'Papagei'),
  ('tiere', 'Möwe'),
  ('tiere', 'Marienkäfer'),
  ('essen', 'Pizza'),
  ('essen', 'Brot'),
  ('essen', 'Butter'),
  ('essen', 'Käse'),
  ('essen', 'Milch'),
  ('essen', 'Joghurt'),
  ('essen', 'Apfel'),
  ('essen', 'Banane'),
  ('essen', 'Erdbeere'),
  ('essen', 'Kirsche'),
  ('essen', 'Weintraube'),
  ('essen', 'Zitrone'),
  ('essen', 'Kartoffel'),
  ('essen', 'Möhre'),
  ('essen', 'Gurke'),
  ('essen', 'Tomate'),
  ('essen', 'Zwiebel'),
  ('essen', 'Knoblauch'),
  ('essen', 'Salat'),
  ('essen', 'Reis'),
  ('essen', 'Nudeln'),
  ('essen', 'Suppe'),
  ('essen', 'Braten'),
  ('essen', 'Schnitzel'),
  ('essen', 'Wurst'),
  ('essen', 'Schinken'),
  ('essen', 'Spiegelei'),
  ('essen', 'Pfannkuchen'),
  ('essen', 'Kuchen'),
  ('essen', 'Torte'),
  ('essen', 'Keks'),
  ('essen', 'Schokolade'),
  ('essen', 'Speiseeis'),
  ('essen', 'Honig'),
  ('essen', 'Marmelade'),
  ('essen', 'Müsli'),
  ('essen', 'Brötchen'),
  ('essen', 'Brezel'),
  ('essen', 'Pommes'),
  ('essen', 'Currywurst'),
  ('essen', 'Döner'),
  ('essen', 'Kaffee'),
  ('essen', 'Tee'),
  ('essen', 'Kakao'),
  ('essen', 'Limonade'),
  ('essen', 'Apfelsaft'),
  ('essen', 'Mineralwasser'),
  ('essen', 'Bier'),
  ('essen', 'Wein'),
  ('essen', 'Sekt'),
  ('berufe', 'Arzt'),
  ('berufe', 'Krankenschwester'),
  ('berufe', 'Lehrer'),
  ('berufe', 'Erzieher'),
  ('berufe', 'Polizist'),
  ('berufe', 'Feuerwehrmann'),
  ('berufe', 'Bäcker'),
  ('berufe', 'Metzger'),
  ('berufe', 'Koch'),
  ('berufe', 'Kellner'),
  ('berufe', 'Friseur'),
  ('berufe', 'Gärtner'),
  ('berufe', 'Landwirt'),
  ('berufe', 'Tierarzt'),
  ('berufe', 'Apotheker'),
  ('berufe', 'Zahnarzt'),
  ('berufe', 'Anwalt'),
  ('berufe', 'Richter'),
  ('berufe', 'Bankkaufmann'),
  ('berufe', 'Verkäufer'),
  ('berufe', 'Kassierer'),
  ('berufe', 'Postbote'),
  ('berufe', 'Busfahrer'),
  ('berufe', 'Lokführer'),
  ('berufe', 'Pilot'),
  ('berufe', 'Flugbegleiter'),
  ('berufe', 'Kapitän'),
  ('berufe', 'Elektriker'),
  ('berufe', 'Klempner'),
  ('berufe', 'Maler'),
  ('berufe', 'Maurer'),
  ('berufe', 'Dachdecker'),
  ('berufe', 'Schreiner'),
  ('berufe', 'Mechaniker'),
  ('berufe', 'Ingenieur'),
  ('berufe', 'Architekt'),
  ('berufe', 'Programmierer'),
  ('berufe', 'Journalist'),
  ('berufe', 'Fotograf'),
  ('berufe', 'Musiker'),
  ('berufe', 'Schauspieler'),
  ('berufe', 'Sänger'),
  ('berufe', 'Bibliothekar'),
  ('berufe', 'Hausmeister'),
  ('berufe', 'Reinigungskraft'),
  ('berufe', 'Schornsteinfeger'),
  ('berufe', 'Optiker'),
  ('berufe', 'Physiotherapeut'),
  ('berufe', 'Steuerberater'),
  ('berufe', 'Soldat'),
  ('sport', 'Fußball'),
  ('sport', 'Handball'),
  ('sport', 'Basketball'),
  ('sport', 'Volleyball'),
  ('sport', 'Tennis'),
  ('sport', 'Tischtennis'),
  ('sport', 'Badminton'),
  ('sport', 'Golf'),
  ('sport', 'Hockey'),
  ('sport', 'Eishockey'),
  ('sport', 'Schwimmen'),
  ('sport', 'Tauchen'),
  ('sport', 'Rudern'),
  ('sport', 'Segeln'),
  ('sport', 'Surfen'),
  ('sport', 'Klettern'),
  ('sport', 'Wandern'),
  ('sport', 'Joggen'),
  ('sport', 'Marathon'),
  ('sport', 'Radfahren'),
  ('sport', 'Mountainbike'),
  ('sport', 'Reiten'),
  ('sport', 'Turnen'),
  ('sport', 'Leichtathletik'),
  ('sport', 'Weitsprung'),
  ('sport', 'Hochsprung'),
  ('sport', 'Speerwurf'),
  ('sport', 'Kugelstoßen'),
  ('sport', 'Boxen'),
  ('sport', 'Judo'),
  ('sport', 'Karate'),
  ('sport', 'Ringen'),
  ('sport', 'Fechten'),
  ('sport', 'Skifahren'),
  ('sport', 'Snowboard'),
  ('sport', 'Rodeln'),
  ('sport', 'Eiskunstlauf'),
  ('sport', 'Biathlon'),
  ('sport', 'Skispringen'),
  ('sport', 'Bogenschießen'),
  ('sport', 'Sportschießen'),
  ('sport', 'Kegeln'),
  ('sport', 'Bowling'),
  ('sport', 'Dart'),
  ('sport', 'Billard'),
  ('sport', 'Yoga'),
  ('sport', 'Pilates'),
  ('sport', 'Krafttraining'),
  ('sport', 'Rennrad'),
  ('sport', 'Triathlon'),
  ('reisen', 'Strand'),
  ('reisen', 'Berg'),
  ('reisen', 'Insel'),
  ('reisen', 'Wüste'),
  ('reisen', 'Dschungel'),
  ('reisen', 'Hotel'),
  ('reisen', 'Ferienwohnung'),
  ('reisen', 'Campingplatz'),
  ('reisen', 'Zelt'),
  ('reisen', 'Wohnwagen'),
  ('reisen', 'Flughafen'),
  ('reisen', 'Bahnhof'),
  ('reisen', 'Hafen'),
  ('reisen', 'Fähre'),
  ('reisen', 'Kreuzfahrt'),
  ('reisen', 'Reisebüro'),
  ('reisen', 'Koffer'),
  ('reisen', 'Rucksack'),
  ('reisen', 'Reisepass'),
  ('reisen', 'Landkarte'),
  ('reisen', 'Stadtführung'),
  ('reisen', 'Museum'),
  ('reisen', 'Schloss'),
  ('reisen', 'Burg'),
  ('reisen', 'Leuchtturm'),
  ('reisen', 'Wasserfall'),
  ('reisen', 'Höhle'),
  ('reisen', 'Bergsee'),
  ('reisen', 'Fluss'),
  ('reisen', 'Meer'),
  ('reisen', 'Alpen'),
  ('reisen', 'Nordsee'),
  ('reisen', 'Ostsee'),
  ('reisen', 'Schwarzwald'),
  ('reisen', 'Bodensee'),
  ('reisen', 'Rom'),
  ('reisen', 'Paris'),
  ('reisen', 'London'),
  ('reisen', 'Wien'),
  ('reisen', 'Amsterdam'),
  ('reisen', 'Barcelona'),
  ('reisen', 'Prag'),
  ('reisen', 'Venedig'),
  ('reisen', 'Mallorca'),
  ('reisen', 'Türkei'),
  ('reisen', 'Italien'),
  ('reisen', 'Norwegen'),
  ('reisen', 'Kanada'),
  ('reisen', 'Japan'),
  ('reisen', 'Ägypten'),
  ('technik', 'Handy'),
  ('technik', 'Tablet'),
  ('technik', 'Laptop'),
  ('technik', 'Computer'),
  ('technik', 'Monitor'),
  ('technik', 'Tastatur'),
  ('technik', 'Maus'),
  ('technik', 'Drucker'),
  ('technik', 'Scanner'),
  ('technik', 'Router'),
  ('technik', 'WLAN'),
  ('technik', 'Bluetooth'),
  ('technik', 'USB-Stick'),
  ('technik', 'Festplatte'),
  ('technik', 'Kopfhörer'),
  ('technik', 'Lautsprecher'),
  ('technik', 'Fernseher'),
  ('technik', 'Fernbedienung'),
  ('technik', 'Beamer'),
  ('technik', 'Kamera'),
  ('technik', 'Drohne'),
  ('technik', 'Smartwatch'),
  ('technik', 'Ladekabel'),
  ('technik', 'Powerbank'),
  ('technik', 'Steckdose'),
  ('technik', 'Batterie'),
  ('technik', 'Solarzelle'),
  ('technik', 'Windrad'),
  ('technik', 'Roboter'),
  ('technik', 'Sprachassistent'),
  ('technik', 'App'),
  ('technik', 'Passwort'),
  ('technik', 'E-Mail'),
  ('technik', 'Suchmaschine'),
  ('technik', 'Videoanruf'),
  ('technik', 'Streaming'),
  ('technik', 'Update'),
  ('technik', 'Virenscanner'),
  ('technik', 'Taschenlampe'),
  ('technik', 'Mikrowelle'),
  ('technik', 'Waschmaschine'),
  ('technik', 'Staubsauger'),
  ('technik', 'Kühlschrank'),
  ('technik', 'Spülmaschine'),
  ('technik', 'Bohrmaschine'),
  ('technik', 'Rasenmäher'),
  ('technik', 'Navigationsgerät'),
  ('technik', 'Klimaanlage'),
  ('technik', 'Nähmaschine'),
  ('technik', 'Wärmepumpe'),
  ('filme', 'Titanic'),
  ('filme', 'Avatar'),
  ('filme', 'Matrix'),
  ('filme', 'Gladiator'),
  ('filme', 'Rocky'),
  ('filme', 'Terminator'),
  ('filme', 'Jurassic Park'),
  ('filme', 'Star Wars'),
  ('filme', 'Herr der Ringe'),
  ('filme', 'Harry Potter'),
  ('filme', 'Der Pate'),
  ('filme', 'Forrest Gump'),
  ('filme', 'Findet Nemo'),
  ('filme', 'König der Löwen'),
  ('filme', 'Shrek'),
  ('filme', 'Die Eiskönigin'),
  ('filme', 'Minions'),
  ('filme', 'Toy Story'),
  ('filme', 'Ice Age'),
  ('filme', 'Das Dschungelbuch'),
  ('filme', 'Tatort'),
  ('filme', 'Lindenstraße'),
  ('filme', 'Die Sendung mit der Maus'),
  ('filme', 'Tagesschau'),
  ('filme', 'Big Bang Theory'),
  ('filme', 'Friends'),
  ('filme', 'Die Simpsons'),
  ('filme', 'Game of Thrones'),
  ('filme', 'Stranger Things'),
  ('filme', 'Breaking Bad'),
  ('filme', 'Dark'),
  ('filme', 'Kinosaal'),
  ('filme', 'Popcorn'),
  ('filme', 'Filmmusik'),
  ('filme', 'Abspann'),
  ('filme', 'Regisseur'),
  ('filme', 'Drehbuch'),
  ('filme', 'Trailer'),
  ('filme', 'Hauptrolle'),
  ('filme', 'Statist'),
  ('filme', 'Kostüm'),
  ('filme', 'Kulisse'),
  ('filme', 'Oscar'),
  ('filme', 'Serienfinale'),
  ('filme', 'Fortsetzung'),
  ('filme', 'Zeichentrick'),
  ('filme', 'Dokumentation'),
  ('filme', 'Krimi'),
  ('filme', 'Western'),
  ('filme', 'Filmpremiere'),
  ('musik', 'Gitarre'),
  ('musik', 'E-Gitarre'),
  ('musik', 'Bass'),
  ('musik', 'Schlagzeug'),
  ('musik', 'Klavier'),
  ('musik', 'Flügel'),
  ('musik', 'Geige'),
  ('musik', 'Cello'),
  ('musik', 'Kontrabass'),
  ('musik', 'Querflöte'),
  ('musik', 'Blockflöte'),
  ('musik', 'Klarinette'),
  ('musik', 'Saxofon'),
  ('musik', 'Trompete'),
  ('musik', 'Posaune'),
  ('musik', 'Tuba'),
  ('musik', 'Waldhorn'),
  ('musik', 'Harfe'),
  ('musik', 'Akkordeon'),
  ('musik', 'Mundharmonika'),
  ('musik', 'Xylofon'),
  ('musik', 'Triangel'),
  ('musik', 'Tamburin'),
  ('musik', 'Orgel'),
  ('musik', 'Keyboard'),
  ('musik', 'Mikrofon'),
  ('musik', 'Chor'),
  ('musik', 'Orchester'),
  ('musik', 'Band'),
  ('musik', 'Dirigent'),
  ('musik', 'Konzert'),
  ('musik', 'Festival'),
  ('musik', 'Noten'),
  ('musik', 'Takt'),
  ('musik', 'Refrain'),
  ('musik', 'Strophe'),
  ('musik', 'Melodie'),
  ('musik', 'Rhythmus'),
  ('musik', 'Schlager'),
  ('musik', 'Rock'),
  ('musik', 'Pop'),
  ('musik', 'Jazz'),
  ('musik', 'Klassik'),
  ('musik', 'Hip-Hop'),
  ('musik', 'Techno'),
  ('musik', 'Volksmusik'),
  ('musik', 'Blaskapelle'),
  ('musik', 'Radio'),
  ('musik', 'Plattenspieler'),
  ('musik', 'Ohrwurm'),
  ('schule', 'Tafel'),
  ('schule', 'Kreide'),
  ('schule', 'Whiteboard'),
  ('schule', 'Schulheft'),
  ('schule', 'Schulbuch'),
  ('schule', 'Federmappe'),
  ('schule', 'Bleistift'),
  ('schule', 'Kugelschreiber'),
  ('schule', 'Radiergummi'),
  ('schule', 'Lineal'),
  ('schule', 'Zirkel'),
  ('schule', 'Geodreieck'),
  ('schule', 'Taschenrechner'),
  ('schule', 'Schulranzen'),
  ('schule', 'Pausenbrot'),
  ('schule', 'Pausenhof'),
  ('schule', 'Schulklingel'),
  ('schule', 'Stundenplan'),
  ('schule', 'Hausaufgaben'),
  ('schule', 'Klassenarbeit'),
  ('schule', 'Diktat'),
  ('schule', 'Zeugnis'),
  ('schule', 'Schulnote'),
  ('schule', 'Sitzenbleiben'),
  ('schule', 'Klassenfahrt'),
  ('schule', 'Wandertag'),
  ('schule', 'Schulbus'),
  ('schule', 'Turnhalle'),
  ('schule', 'Sportunterricht'),
  ('schule', 'Mathematik'),
  ('schule', 'Deutsch'),
  ('schule', 'Englisch'),
  ('schule', 'Französisch'),
  ('schule', 'Biologie'),
  ('schule', 'Chemie'),
  ('schule', 'Physik'),
  ('schule', 'Erdkunde'),
  ('schule', 'Geschichte'),
  ('schule', 'Kunstunterricht'),
  ('schule', 'Musikunterricht'),
  ('schule', 'Religion'),
  ('schule', 'Werken'),
  ('schule', 'Lehrerzimmer'),
  ('schule', 'Sekretariat'),
  ('schule', 'Schulleiter'),
  ('schule', 'Klassensprecher'),
  ('schule', 'Elternabend'),
  ('schule', 'Abitur'),
  ('schule', 'Sommerferien'),
  ('schule', 'Schulhof'),
  ('haus', 'Wohnzimmer'),
  ('haus', 'Schlafzimmer'),
  ('haus', 'Kinderzimmer'),
  ('haus', 'Küche'),
  ('haus', 'Badezimmer'),
  ('haus', 'Flur'),
  ('haus', 'Keller'),
  ('haus', 'Dachboden'),
  ('haus', 'Garage'),
  ('haus', 'Balkon'),
  ('haus', 'Terrasse'),
  ('haus', 'Garten'),
  ('haus', 'Treppe'),
  ('haus', 'Fenster'),
  ('haus', 'Haustür'),
  ('haus', 'Dach'),
  ('haus', 'Schornstein'),
  ('haus', 'Sofa'),
  ('haus', 'Sessel'),
  ('haus', 'Couchtisch'),
  ('haus', 'Esstisch'),
  ('haus', 'Stuhl'),
  ('haus', 'Bett'),
  ('haus', 'Matratze'),
  ('haus', 'Kissen'),
  ('haus', 'Bettdecke'),
  ('haus', 'Kleiderschrank'),
  ('haus', 'Kommode'),
  ('haus', 'Regal'),
  ('haus', 'Bücherregal'),
  ('haus', 'Teppich'),
  ('haus', 'Vorhang'),
  ('haus', 'Lampe'),
  ('haus', 'Kronleuchter'),
  ('haus', 'Spiegel'),
  ('haus', 'Bilderrahmen'),
  ('haus', 'Blumentopf'),
  ('haus', 'Herd'),
  ('haus', 'Backofen'),
  ('haus', 'Spüle'),
  ('haus', 'Wasserhahn'),
  ('haus', 'Badewanne'),
  ('haus', 'Dusche'),
  ('haus', 'Waschbecken'),
  ('haus', 'Heizung'),
  ('haus', 'Türklinke'),
  ('haus', 'Briefkasten'),
  ('haus', 'Zaun'),
  ('haus', 'Hecke'),
  ('haus', 'Gartenzwerg'),
  ('natur', 'Sonne'),
  ('natur', 'Mond'),
  ('natur', 'Sterne'),
  ('natur', 'Wolke'),
  ('natur', 'Regen'),
  ('natur', 'Schnee'),
  ('natur', 'Hagel'),
  ('natur', 'Nebel'),
  ('natur', 'Wind'),
  ('natur', 'Sturm'),
  ('natur', 'Gewitter'),
  ('natur', 'Blitz'),
  ('natur', 'Donner'),
  ('natur', 'Regenbogen'),
  ('natur', 'Frost'),
  ('natur', 'Raureif'),
  ('natur', 'Morgentau'),
  ('natur', 'Hitze'),
  ('natur', 'Dürre'),
  ('natur', 'Überschwemmung'),
  ('natur', 'Lawine'),
  ('natur', 'Erdbeben'),
  ('natur', 'Vulkan'),
  ('natur', 'Gletscher'),
  ('natur', 'Wald'),
  ('natur', 'Wiese'),
  ('natur', 'Feld'),
  ('natur', 'Moor'),
  ('natur', 'Sumpf'),
  ('natur', 'Baum'),
  ('natur', 'Eiche'),
  ('natur', 'Buche'),
  ('natur', 'Tanne'),
  ('natur', 'Birke'),
  ('natur', 'Blume'),
  ('natur', 'Rose'),
  ('natur', 'Tulpe'),
  ('natur', 'Sonnenblume'),
  ('natur', 'Gänseblümchen'),
  ('natur', 'Löwenzahn'),
  ('natur', 'Klee'),
  ('natur', 'Moos'),
  ('natur', 'Pilz'),
  ('natur', 'Farn'),
  ('natur', 'Bach'),
  ('natur', 'Teich'),
  ('natur', 'Quelle'),
  ('natur', 'Küste'),
  ('natur', 'Düne'),
  ('natur', 'Herbstlaub'),
  ('koerper', 'Kopf'),
  ('koerper', 'Haar'),
  ('koerper', 'Stirn'),
  ('koerper', 'Auge'),
  ('koerper', 'Augenbraue'),
  ('koerper', 'Wimper'),
  ('koerper', 'Nase'),
  ('koerper', 'Mund'),
  ('koerper', 'Lippe'),
  ('koerper', 'Zahn'),
  ('koerper', 'Zunge'),
  ('koerper', 'Kinn'),
  ('koerper', 'Ohr'),
  ('koerper', 'Hals'),
  ('koerper', 'Nacken'),
  ('koerper', 'Schulter'),
  ('koerper', 'Arm'),
  ('koerper', 'Ellenbogen'),
  ('koerper', 'Handgelenk'),
  ('koerper', 'Hand'),
  ('koerper', 'Finger'),
  ('koerper', 'Daumen'),
  ('koerper', 'Fingernagel'),
  ('koerper', 'Brustkorb'),
  ('koerper', 'Bauch'),
  ('koerper', 'Rücken'),
  ('koerper', 'Hüfte'),
  ('koerper', 'Bein'),
  ('koerper', 'Knie'),
  ('koerper', 'Wade'),
  ('koerper', 'Knöchel'),
  ('koerper', 'Fuß'),
  ('koerper', 'Zeh'),
  ('koerper', 'Ferse'),
  ('koerper', 'Haut'),
  ('koerper', 'Muskel'),
  ('koerper', 'Knochen'),
  ('koerper', 'Herz'),
  ('koerper', 'Lunge'),
  ('koerper', 'Magen'),
  ('koerper', 'Leber'),
  ('koerper', 'Niere'),
  ('koerper', 'Gehirn'),
  ('koerper', 'Blut'),
  ('koerper', 'Puls'),
  ('koerper', 'Fieber'),
  ('koerper', 'Husten'),
  ('koerper', 'Schnupfen'),
  ('koerper', 'Kopfschmerzen'),
  ('koerper', 'Pflaster'),
  ('kleidung', 'Hemd'),
  ('kleidung', 'Bluse'),
  ('kleidung', 'T-Shirt'),
  ('kleidung', 'Pullover'),
  ('kleidung', 'Strickjacke'),
  ('kleidung', 'Weste'),
  ('kleidung', 'Jacke'),
  ('kleidung', 'Mantel'),
  ('kleidung', 'Anorak'),
  ('kleidung', 'Regenjacke'),
  ('kleidung', 'Hose'),
  ('kleidung', 'Jeans'),
  ('kleidung', 'Shorts'),
  ('kleidung', 'Rock'),
  ('kleidung', 'Kleid'),
  ('kleidung', 'Anzug'),
  ('kleidung', 'Krawatte'),
  ('kleidung', 'Fliege'),
  ('kleidung', 'Gürtel'),
  ('kleidung', 'Hosenträger'),
  ('kleidung', 'Socken'),
  ('kleidung', 'Strumpfhose'),
  ('kleidung', 'Unterhemd'),
  ('kleidung', 'Schlafanzug'),
  ('kleidung', 'Bademantel'),
  ('kleidung', 'Badehose'),
  ('kleidung', 'Badeanzug'),
  ('kleidung', 'Bikini'),
  ('kleidung', 'Turnschuhe'),
  ('kleidung', 'Sandalen'),
  ('kleidung', 'Stiefel'),
  ('kleidung', 'Gummistiefel'),
  ('kleidung', 'Hausschuhe'),
  ('kleidung', 'Wanderschuhe'),
  ('kleidung', 'Mütze'),
  ('kleidung', 'Hut'),
  ('kleidung', 'Kappe'),
  ('kleidung', 'Schal'),
  ('kleidung', 'Handschuhe'),
  ('kleidung', 'Halstuch'),
  ('kleidung', 'Brille'),
  ('kleidung', 'Sonnenbrille'),
  ('kleidung', 'Armbanduhr'),
  ('kleidung', 'Ring'),
  ('kleidung', 'Halskette'),
  ('kleidung', 'Ohrring'),
  ('kleidung', 'Handtasche'),
  ('kleidung', 'Geldbeutel'),
  ('kleidung', 'Regenschirm'),
  ('kleidung', 'Lätzchen'),
  ('fahrzeuge', 'Auto'),
  ('fahrzeuge', 'Fahrrad'),
  ('fahrzeuge', 'Motorrad'),
  ('fahrzeuge', 'Roller'),
  ('fahrzeuge', 'Moped'),
  ('fahrzeuge', 'Lastwagen'),
  ('fahrzeuge', 'Lieferwagen'),
  ('fahrzeuge', 'Bus'),
  ('fahrzeuge', 'Reisebus'),
  ('fahrzeuge', 'Straßenbahn'),
  ('fahrzeuge', 'U-Bahn'),
  ('fahrzeuge', 'S-Bahn'),
  ('fahrzeuge', 'Zug'),
  ('fahrzeuge', 'Lokomotive'),
  ('fahrzeuge', 'Güterzug'),
  ('fahrzeuge', 'Taxi'),
  ('fahrzeuge', 'Krankenwagen'),
  ('fahrzeuge', 'Feuerwehrauto'),
  ('fahrzeuge', 'Polizeiauto'),
  ('fahrzeuge', 'Müllwagen'),
  ('fahrzeuge', 'Traktor'),
  ('fahrzeuge', 'Mähdrescher'),
  ('fahrzeuge', 'Bagger'),
  ('fahrzeuge', 'Kran'),
  ('fahrzeuge', 'Gabelstapler'),
  ('fahrzeuge', 'Betonmischer'),
  ('fahrzeuge', 'Schneepflug'),
  ('fahrzeuge', 'Wohnmobil'),
  ('fahrzeuge', 'Anhänger'),
  ('fahrzeuge', 'Cabrio'),
  ('fahrzeuge', 'Geländewagen'),
  ('fahrzeuge', 'Sportwagen'),
  ('fahrzeuge', 'Oldtimer'),
  ('fahrzeuge', 'Rennwagen'),
  ('fahrzeuge', 'Flugzeug'),
  ('fahrzeuge', 'Hubschrauber'),
  ('fahrzeuge', 'Segelflugzeug'),
  ('fahrzeuge', 'Heißluftballon'),
  ('fahrzeuge', 'Rakete'),
  ('fahrzeuge', 'Schiff'),
  ('fahrzeuge', 'Segelboot'),
  ('fahrzeuge', 'Ruderboot'),
  ('fahrzeuge', 'Kanu'),
  ('fahrzeuge', 'Schlauchboot'),
  ('fahrzeuge', 'U-Boot'),
  ('fahrzeuge', 'Jetski'),
  ('fahrzeuge', 'Seilbahn'),
  ('fahrzeuge', 'Skilift'),
  ('fahrzeuge', 'Rollstuhl'),
  ('fahrzeuge', 'Tretroller'),
  ('spiele', 'Schach'),
  ('spiele', 'Dame'),
  ('spiele', 'Mühle'),
  ('spiele', 'Halma'),
  ('spiele', 'Backgammon'),
  ('spiele', 'Mensch ärgere dich nicht'),
  ('spiele', 'Monopoly'),
  ('spiele', 'Scrabble'),
  ('spiele', 'Risiko'),
  ('spiele', 'Die Siedler von Catan'),
  ('spiele', 'Uno'),
  ('spiele', 'Skat'),
  ('spiele', 'Doppelkopf'),
  ('spiele', 'Rommé'),
  ('spiele', 'Mau-Mau'),
  ('spiele', 'Poker'),
  ('spiele', 'Memory'),
  ('spiele', 'Puzzle'),
  ('spiele', 'Domino'),
  ('spiele', 'Kniffel'),
  ('spiele', 'Bingo'),
  ('spiele', 'Sudoku'),
  ('spiele', 'Kreuzworträtsel'),
  ('spiele', 'Verstecken'),
  ('spiele', 'Fangen'),
  ('spiele', 'Blinde Kuh'),
  ('spiele', 'Topfschlagen'),
  ('spiele', 'Reise nach Jerusalem'),
  ('spiele', 'Stille Post'),
  ('spiele', 'Sackhüpfen'),
  ('spiele', 'Gummitwist'),
  ('spiele', 'Seilspringen'),
  ('spiele', 'Hüpfkästchen'),
  ('spiele', 'Murmeln'),
  ('spiele', 'Drachensteigen'),
  ('spiele', 'Sandburg'),
  ('spiele', 'Schaukel'),
  ('spiele', 'Rutsche'),
  ('spiele', 'Wippe'),
  ('spiele', 'Klettergerüst'),
  ('spiele', 'Lego'),
  ('spiele', 'Playmobil'),
  ('spiele', 'Modelleisenbahn'),
  ('spiele', 'Sammelalbum'),
  ('spiele', 'Briefmarken'),
  ('spiele', 'Stricken'),
  ('spiele', 'Häkeln'),
  ('spiele', 'Basteln'),
  ('spiele', 'Gartenarbeit'),
  ('spiele', 'Angeln'),
  ('feiertage', 'Weihnachten'),
  ('feiertage', 'Heiligabend'),
  ('feiertage', 'Silvester'),
  ('feiertage', 'Neujahr'),
  ('feiertage', 'Ostern'),
  ('feiertage', 'Karfreitag'),
  ('feiertage', 'Pfingsten'),
  ('feiertage', 'Fronleichnam'),
  ('feiertage', 'Christi Himmelfahrt'),
  ('feiertage', 'Nikolaus'),
  ('feiertage', 'Advent'),
  ('feiertage', 'Adventskranz'),
  ('feiertage', 'Weihnachtsbaum'),
  ('feiertage', 'Krippe'),
  ('feiertage', 'Weihnachtsmarkt'),
  ('feiertage', 'Plätzchen'),
  ('feiertage', 'Osterhase'),
  ('feiertage', 'Ostereier'),
  ('feiertage', 'Eiersuche'),
  ('feiertage', 'Karneval'),
  ('feiertage', 'Fasching'),
  ('feiertage', 'Rosenmontag'),
  ('feiertage', 'Aschermittwoch'),
  ('feiertage', 'Muttertag'),
  ('feiertage', 'Vatertag'),
  ('feiertage', 'Valentinstag'),
  ('feiertage', 'Halloween'),
  ('feiertage', 'Erntedankfest'),
  ('feiertage', 'Martinstag'),
  ('feiertage', 'Laternenumzug'),
  ('feiertage', 'Schützenfest'),
  ('feiertage', 'Oktoberfest'),
  ('feiertage', 'Kirmes'),
  ('feiertage', 'Jahrmarkt'),
  ('feiertage', 'Geburtstag'),
  ('feiertage', 'Geburtstagstorte'),
  ('feiertage', 'Hochzeit'),
  ('feiertage', 'Polterabend'),
  ('feiertage', 'Taufe'),
  ('feiertage', 'Kommunion'),
  ('feiertage', 'Konfirmation'),
  ('feiertage', 'Jubiläum'),
  ('feiertage', 'Richtfest'),
  ('feiertage', 'Einschulung'),
  ('feiertage', 'Abschlussfeier'),
  ('feiertage', 'Feuerwerk'),
  ('feiertage', 'Girlande'),
  ('feiertage', 'Luftballon'),
  ('feiertage', 'Geschenk'),
  ('feiertage', 'Festessen'),
  ('gefuehle', 'Freude'),
  ('gefuehle', 'Glück'),
  ('gefuehle', 'Liebe'),
  ('gefuehle', 'Zuneigung'),
  ('gefuehle', 'Stolz'),
  ('gefuehle', 'Dankbarkeit'),
  ('gefuehle', 'Erleichterung'),
  ('gefuehle', 'Hoffnung'),
  ('gefuehle', 'Vorfreude'),
  ('gefuehle', 'Neugier'),
  ('gefuehle', 'Begeisterung'),
  ('gefuehle', 'Zufriedenheit'),
  ('gefuehle', 'Geborgenheit'),
  ('gefuehle', 'Mitgefühl'),
  ('gefuehle', 'Sehnsucht'),
  ('gefuehle', 'Heimweh'),
  ('gefuehle', 'Fernweh'),
  ('gefuehle', 'Traurigkeit'),
  ('gefuehle', 'Kummer'),
  ('gefuehle', 'Enttäuschung'),
  ('gefuehle', 'Wut'),
  ('gefuehle', 'Ärger'),
  ('gefuehle', 'Zorn'),
  ('gefuehle', 'Frust'),
  ('gefuehle', 'Neid'),
  ('gefuehle', 'Eifersucht'),
  ('gefuehle', 'Angst'),
  ('gefuehle', 'Panik'),
  ('gefuehle', 'Sorge'),
  ('gefuehle', 'Nervosität'),
  ('gefuehle', 'Aufregung'),
  ('gefuehle', 'Scham'),
  ('gefuehle', 'Schuldgefühl'),
  ('gefuehle', 'Verlegenheit'),
  ('gefuehle', 'Peinlichkeit'),
  ('gefuehle', 'Langeweile'),
  ('gefuehle', 'Müdigkeit'),
  ('gefuehle', 'Erschöpfung'),
  ('gefuehle', 'Überraschung'),
  ('gefuehle', 'Verwirrung'),
  ('gefuehle', 'Zweifel'),
  ('gefuehle', 'Misstrauen'),
  ('gefuehle', 'Einsamkeit'),
  ('gefuehle', 'Heiterkeit'),
  ('gefuehle', 'Schadenfreude'),
  ('gefuehle', 'Gelassenheit'),
  ('gefuehle', 'Ungeduld'),
  ('gefuehle', 'Respekt'),
  ('gefuehle', 'Bewunderung'),
  ('gefuehle', 'Zuversicht'),
  ('stadt', 'Rathaus'),
  ('stadt', 'Marktplatz'),
  ('stadt', 'Kirche'),
  ('stadt', 'Dom'),
  ('stadt', 'Bushaltestelle'),
  ('stadt', 'Fußgängerzone'),
  ('stadt', 'Einkaufszentrum'),
  ('stadt', 'Supermarkt'),
  ('stadt', 'Bäckerei'),
  ('stadt', 'Metzgerei'),
  ('stadt', 'Apotheke'),
  ('stadt', 'Drogerie'),
  ('stadt', 'Buchhandlung'),
  ('stadt', 'Blumenladen'),
  ('stadt', 'Kiosk'),
  ('stadt', 'Postfiliale'),
  ('stadt', 'Bank'),
  ('stadt', 'Geldautomat'),
  ('stadt', 'Bibliothek'),
  ('stadt', 'Schwimmbad'),
  ('stadt', 'Sporthalle'),
  ('stadt', 'Stadion'),
  ('stadt', 'Kino'),
  ('stadt', 'Theater'),
  ('stadt', 'Stadtmuseum'),
  ('stadt', 'Zoo'),
  ('stadt', 'Stadtpark'),
  ('stadt', 'Spielplatz'),
  ('stadt', 'Friedhof'),
  ('stadt', 'Krankenhaus'),
  ('stadt', 'Feuerwache'),
  ('stadt', 'Polizeirevier'),
  ('stadt', 'Ampel'),
  ('stadt', 'Zebrastreifen'),
  ('stadt', 'Kreisverkehr'),
  ('stadt', 'Parkhaus'),
  ('stadt', 'Baustelle'),
  ('stadt', 'Straßenlaterne'),
  ('stadt', 'Mülleimer'),
  ('stadt', 'Parkbank'),
  ('stadt', 'Brunnen'),
  ('stadt', 'Denkmal'),
  ('stadt', 'Brücke'),
  ('stadt', 'Tunnel'),
  ('stadt', 'Stau'),
  ('stadt', 'Radweg'),
  ('stadt', 'Bürgersteig'),
  ('stadt', 'Hochhaus'),
  ('stadt', 'Fahrkartenautomat'),
  ('stadt', 'Wochenmarkt'),
  ('maerchen', 'Schneewittchen'),
  ('maerchen', 'Aschenputtel'),
  ('maerchen', 'Dornröschen'),
  ('maerchen', 'Rotkäppchen'),
  ('maerchen', 'Rapunzel'),
  ('maerchen', 'Hänsel und Gretel'),
  ('maerchen', 'Frau Holle'),
  ('maerchen', 'Rumpelstilzchen'),
  ('maerchen', 'Der Froschkönig'),
  ('maerchen', 'Die Bremer Stadtmusikanten'),
  ('maerchen', 'Der gestiefelte Kater'),
  ('maerchen', 'Tischlein deck dich'),
  ('maerchen', 'Das tapfere Schneiderlein'),
  ('maerchen', 'Die Sterntaler'),
  ('maerchen', 'Der Wolf und die sieben Geißlein'),
  ('maerchen', 'Peter Pan'),
  ('maerchen', 'Pinocchio'),
  ('maerchen', 'Alice im Wunderland'),
  ('maerchen', 'Der kleine Prinz'),
  ('maerchen', 'Robin Hood'),
  ('maerchen', 'König Artus'),
  ('maerchen', 'Drache'),
  ('maerchen', 'Ritter'),
  ('maerchen', 'Prinzessin'),
  ('maerchen', 'Prinz'),
  ('maerchen', 'König'),
  ('maerchen', 'Königin'),
  ('maerchen', 'Hexe'),
  ('maerchen', 'Zauberer'),
  ('maerchen', 'Fee'),
  ('maerchen', 'Elfe'),
  ('maerchen', 'Zwerg'),
  ('maerchen', 'Riese'),
  ('maerchen', 'Troll'),
  ('maerchen', 'Kobold'),
  ('maerchen', 'Einhorn'),
  ('maerchen', 'Meerjungfrau'),
  ('maerchen', 'Vampir'),
  ('maerchen', 'Werwolf'),
  ('maerchen', 'Gespenst'),
  ('maerchen', 'Zauberstab'),
  ('maerchen', 'Zaubertrank'),
  ('maerchen', 'Zauberspiegel'),
  ('maerchen', 'Märchenschloss'),
  ('maerchen', 'Verwunschener Wald'),
  ('maerchen', 'Goldene Kugel'),
  ('maerchen', 'Glasschuh'),
  ('maerchen', 'Spinnrad'),
  ('maerchen', 'Siebenmeilenstiefel'),
  ('maerchen', 'Wunschbrunnen'),
  ('beruehmt', 'Albert Einstein'),
  ('beruehmt', 'Isaac Newton'),
  ('beruehmt', 'Marie Curie'),
  ('beruehmt', 'Charles Darwin'),
  ('beruehmt', 'Leonardo da Vinci'),
  ('beruehmt', 'Michelangelo'),
  ('beruehmt', 'Vincent van Gogh'),
  ('beruehmt', 'Pablo Picasso'),
  ('beruehmt', 'Ludwig van Beethoven'),
  ('beruehmt', 'Wolfgang Amadeus Mozart'),
  ('beruehmt', 'Johann Sebastian Bach'),
  ('beruehmt', 'Johann Wolfgang von Goethe'),
  ('beruehmt', 'Friedrich Schiller'),
  ('beruehmt', 'Die Gebrüder Grimm'),
  ('beruehmt', 'William Shakespeare'),
  ('beruehmt', 'Astrid Lindgren'),
  ('beruehmt', 'Anne Frank'),
  ('beruehmt', 'Martin Luther'),
  ('beruehmt', 'Martin Luther King'),
  ('beruehmt', 'Mahatma Gandhi'),
  ('beruehmt', 'Nelson Mandela'),
  ('beruehmt', 'Mutter Teresa'),
  ('beruehmt', 'Winston Churchill'),
  ('beruehmt', 'Konrad Adenauer'),
  ('beruehmt', 'Angela Merkel'),
  ('beruehmt', 'Helmut Kohl'),
  ('beruehmt', 'Christoph Kolumbus'),
  ('beruehmt', 'Neil Armstrong'),
  ('beruehmt', 'Alexander von Humboldt'),
  ('beruehmt', 'Karl der Große'),
  ('beruehmt', 'Napoleon'),
  ('beruehmt', 'Kleopatra'),
  ('beruehmt', 'Julius Cäsar'),
  ('beruehmt', 'Elvis Presley'),
  ('beruehmt', 'Michael Jackson'),
  ('beruehmt', 'Die Beatles'),
  ('beruehmt', 'Freddie Mercury'),
  ('beruehmt', 'Marilyn Monroe'),
  ('beruehmt', 'Charlie Chaplin'),
  ('beruehmt', 'Walt Disney'),
  ('beruehmt', 'Steve Jobs'),
  ('beruehmt', 'Bill Gates'),
  ('beruehmt', 'Muhammad Ali'),
  ('beruehmt', 'Pelé'),
  ('beruehmt', 'Franz Beckenbauer'),
  ('beruehmt', 'Michael Schumacher'),
  ('beruehmt', 'Steffi Graf'),
  ('beruehmt', 'Boris Becker'),
  ('beruehmt', 'Dirk Nowitzki'),
  ('beruehmt', 'Usain Bolt')
on conflict (category_id, word) do nothing;
